<i><h1>KFOLD Cross Validation</h1></i>

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [6]:
#Logistic Regression

In [7]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9685185185185186

In [8]:
#Support Vector Machine

In [9]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4962962962962963

In [10]:
#Random Forest

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

In [12]:
#Example For KFold Validation

In [18]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [20]:
#Using KFold For Digits Example

In [21]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [26]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [27]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [28]:
scores_rf

[0.9215358931552587, 0.9432387312186978, 0.9181969949916527]

In [29]:
#Cross_val_score Function

In [30]:
from sklearn.model_selection import cross_val_score

In [45]:
cr = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=10)
np.average(cr)

0.9259745499689634

In [46]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=4)

array([0.40888889, 0.40534521, 0.43207127, 0.50556793])

In [47]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=4)

array([0.93111111, 0.88418708, 0.96213808, 0.93541203])

CROSS VALIDATION SCORE uses Stratifield KFold by Default

<h4>
Parameter tunning using k fold cross validation</h4>

In [48]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8670297951582867

In [49]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9465704531346988

In [50]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9454562383612662

In [51]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9432402234636872