In [1]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('titanic.csv')
df.head(10)

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   
5            6                                   Moran, Mr. James       3   
6            7                            McCarthy, Mr. Timothy J       1   
7            8                     Palsson, Master. Gosta Leonard       3   
8            9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3   
9           10                Nasser, Mrs. Nicholas (Adele Achem)       2   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   
5    male   NaN      0      0            330877   8.4583   NaN        Q   
6    male  54.0      0      0             17463  51.8625   E46        S   
7    male   2.0      3      1            349909  21.0750   NaN        S   
8  female  27.0      0      2            347742  11.1333   NaN        S   
9  female  14.0      1      0            237736  30.0708   NaN        C   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0  
5         0  
6         0  
7         0  
8         1  
9         1

In [19]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [20]:
inputs = df.drop('Survived',axis='columns')
inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [21]:
dummies = pd.get_dummies(inputs.Sex)
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [22]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs

Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [23]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs

Pclass   Age     Fare  female
0         3  22.0   7.2500       0
1         1  38.0  71.2833       1
2         3  26.0   7.9250       1
3         1  35.0  53.1000       1
4         3  35.0   8.0500       0
..      ...   ...      ...     ...
886       2  27.0  13.0000       0
887       1  19.0  30.0000       1
888       3   NaN  23.4500       1
889       1  26.0  30.0000       0
890       3  32.0   7.7500       0

[891 rows x 4 columns]

In [24]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [28]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(7)
target = df.Survived
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split
train_X , test_X , train_y , test_y = train_test_split(inputs,target,test_size=0.2)

In [32]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(train_X,train_y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [33]:
model.predict(test_X)

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0], dtype=int64)

In [34]:
model.score(test_X,test_y)

0.8268156424581006

In [36]:
model.predict_proba(test_X[:10])

array([[0.69197154, 0.30802846],
       [0.92016168, 0.07983832],
       [0.96623648, 0.03376352],
       [0.96586882, 0.03413118],
       [0.27895048, 0.72104952],
       [0.9650787 , 0.0349213 ],
       [0.96077231, 0.03922769],
       [0.09477901, 0.90522099],
       [0.96436471, 0.03563529],
       [0.31358967, 0.68641033]])

<h1 style="color:red">Cross Validation Score</h1>

In [35]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),train_X,train_y,cv=5)


array([0.7972028 , 0.72027972, 0.78169014, 0.71830986, 0.78873239])